import './globals.css'
import 'bootstrap-icons/font/bootstrap-icons.css';
import Navbar from './components/navbar';
import Welcome from "./components/welcome"
import Footer from "./components/footer"

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body >
        <Navbar/>
        <Welcome/>
        <main>
          {children}
          
        </main>
        <Footer/>
      </body>
    </html>
  )
}
